import type { UserRoundRecord } from '../types';

export function createInitialUserRecords(): UserRoundRecord[] {
  const now = Date.now();
  return [
    {
      id: 'rec-init-1',
      roundNumber: 4830,
      game: 'CRASH',
      resultType: 'WIN',
      stake: 200,
      multiplier: 3.45,
      outcomeDisplay: 'Cashed out @ 3.45x',
      profit: 490.0,
      timestamp: now - 35000,
    },
    {
      id: 'rec-init-2',
      roundNumber: 4829,
      game: 'CRASH',
      resultType: 'NOT_PLAYED',
      stake: 0,
      multiplier: 12.8,
      outcomeDisplay: 'Spectated: Crashed @ 12.80x (Mega Rocket)',
      profit: 0,
      timestamp: now - 85000,
    },
    {
      id: 'rec-init-3',
      roundNumber: 4828,
      game: 'CRASH',
      resultType: 'LOSS',
      stake: 150,
      multiplier: 1.15,
      outcomeDisplay: 'Crashed @ 1.15x (Bust)',
      profit: -150.0,
      timestamp: now - 145000,
    },
    {
      id: 'rec-init-4',
      roundNumber: 8920,
      game: 'SUM_DICE',
      resultType: 'WIN',
      stake: 100,
      multiplier: 7.2,
      outcomeDisplay: 'Hit Sum 14 (Big / Even)',
      profit: 620.0,
      timestamp: now - 210000,
    },
    {
      id: 'rec-init-5',
      roundNumber: 4827,
      game: 'CRASH',
      resultType: 'WIN',
      stake: 250,
      multiplier: 2.1,
      outcomeDisplay: 'Cashed out @ 2.10x',
      profit: 275.0,
      timestamp: now - 275000,
    },
    {
      id: 'rec-init-6',
      roundNumber: 4826,
      game: 'CRASH',
      resultType: 'NOT_PLAYED',
      stake: 0,
      multiplier: 1.05,
      outcomeDisplay: 'Spectated: Instant Crash @ 1.05x',
      profit: 0,
      timestamp: now - 340000,
    },
    {
      id: 'rec-init-7',
      roundNumber: 8919,
      game: 'SUM_DICE',
      resultType: 'NOT_PLAYED',
      stake: 0,
      multiplier: 14.5,
      outcomeDisplay: 'Spectated: Sum 19 (Big / Odd)',
      profit: 0,
      timestamp: now - 400000,
    },
    {
      id: 'rec-init-8',
      roundNumber: 4825,
      game: 'CRASH',
      resultType: 'LOSS',
      stake: 100,
      multiplier: 1.42,
      outcomeDisplay: 'Crashed @ 1.42x (Bust)',
      profit: -100.0,
      timestamp: now - 460000,
    },
    {
      id: 'rec-init-9',
      roundNumber: 4824,
      game: 'CRASH',
      resultType: 'WIN',
      stake: 300,
      multiplier: 4.8,
      outcomeDisplay: 'Cashed out @ 4.80x (Super Win)',
      profit: 1140.0,
      timestamp: now - 520000,
    },
  ];
}
